### ISSUE TITLE
Running the code locally

### ISSUE THREAD

**Issue by m4v15** [FACK1/had-am-sa#40]
Good that you have some instructions in your readme, but they could be a bit more detailed:

Should be something more like:
- clone the repo
- run npm i
- run whatever the script is to run in developer mode
- instructions on what to put in a config.env file - this needs to include the variable name, and the type of variable - eg 'create a config.env file and put in a postgres database url, giving it the name DB_URL'
- instructions on how to build the database

**Comment by fdo2** [comment]
It doesn't run locally ,, gives "No database URL" !

**Comment by amanshawar** [comment]
it's done , here : 33741b0abf31641c180c3aadb0dd21ee70e6dbea
